/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.32).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Mdata;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2023-09-19T22:58:06.947Z")

@Validated
@Api(value = "{id}", description = "the {id} API")
@RequestMapping(value = "")
public interface IdApi {

    @ApiOperation(value = "Get data by ID", nickname = "idGet", notes = "", response = Mdata.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response", response = Mdata.class),
        @ApiResponse(code = 404, message = "Data not found") })
    @RequestMapping(value = "/{id}",
        method = RequestMethod.GET)
    ResponseEntity<Mdata> idGet(@ApiParam(value = "ID of the data",required=true) @PathVariable("id") Integer id);

}
